### ISSUE TITLE
Getting this error after training when try to evaluate the model. OSError: Unable to open file (file read failed)

### ISSUE THREAD

**Issue by AliMedVisionTech** [tiangexiang/BiO-Net#2]
python3 train.py --evaluate_only --valid_data /home/ali/BiO-Net-master/monuseg/test/ --model_path /home/ali/BiO-Net-master/checkpoints/1
Using TensorFlow backend.
loading monuseg data...
Successfully loaded data from /home/ali/BiO-Net-master/monuseg/test/
data shape: (112, 512, 512, 3) (112, 512, 512, 1)
Start evaluation...
Restoring model from path: /home/ali/BiO-Net-master/checkpoints/1
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    main()
  File "train.py", line 163, in main
    evaluate(args, val_data)
  File "train.py", line 111, in evaluate
    model = load_model(model_path, compile=False)
  File "/home/ali/anaconda3/envs/test/lib/python3.5/site-packages/keras/models.py", line 237, in load_model
    with h5py.File(filepath, mode='r') as f:
  File "/home/ali/anaconda3/envs/test/lib/python3.5/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/ali/anaconda3/envs/test/lib/python3.5/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file read failed: time = Wed Nov 25 09:15:54 2020
, filename = '/home/ali/BiO-Net-master/checkpoints/1', file descriptor = 22, errno = 21, error message = 'Is a directory', buf = 0x7fff604ba830, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)

**Comment by tiangexiang** [comment]
Hi, this is because the specified model path is not a valid model checkpoint .h5 file (but a directory). The solution is to specify the model file rather than the base path. In your case, please try '--model_path /home/ali/BiO-Net-master/checkpoints/1/MODEL_FILE.h5'. Sorry for the misleading name, it should be --model_file instead:)

**Comment by AliMedVisionTech** [comment]
ok thanks
