### ISSUE TITLE
thanks for updating your code. but when i tried to train the model and getting this error

### ISSUE THREAD

**Issue by AliMedVisionTech** [tiangexiang/BiO-Net#6]
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    CORE = importlib.import_module(args.backend+'_version')
  File "/home/ali/anaconda3/envs/keras/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ali/BiO-Net-master/keras_version/__init__.py", line 1, in <module>
    from .utils import *
  File "/home/ali/BiO-Net-master/keras_version/utils.py", line 21, in <module>
    from .model import *
  File "/home/ali/BiO-Net-master/keras_version/model.py", line 7, in <module>
    from utils import get_augmented
ImportError: cannot import name 'get_augmented'

**Comment by tiangexiang** [comment]
Hi, just for a quick fix, can you try to comment out line 7 in File "/home/ali/BiO-Net-master/keras_version/model.py", to see if it works?

**Comment by AliMedVisionTech** [comment]
yes i have tried and solve the problem. now having a problem with evaluating query 

nonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    main(args, CORE)
  File "main.py", line 40, in main
    if os.path.isfile(args.output_path):
AttributeError: 'Namespace' object has no attribute 'output_path'

**Comment by tiangexiang** [comment]
oops, this issue can be easily fixed by changing 'args.output_path' at line 40, main.py to 'args.model_path'. Sorry for the typos, I will make an update asap.

**Comment by tiangexiang** [comment]
Closing this issue for now, if there is still a problem, feel free to raise another:)
